config/routes.rb
Rails.application.routes.draw do



  get 'admin/home'
  devise_for :admins
  get 'admin_products/index'

  # get 'basket/index'

  devise_for :users
  root to: "home#index"  #home controller, index action (method)

  resources :categories do
    resources :products
  end

  resources :products do
    resources :comments
  end

  resources :products do
    resources :orders
  end

  resources :orders
  resources :customers

  resources :customers do
    resources :orders
  end

  resources :admin

  resources :admin_products

  resources :office

  resources :download
  # get 'admin_products/update'

  resources :products do
    collection { post :import }
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :product
    validates :name, :comment, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders
  belongs_to :user, required: false
  validates :address, :phone, presence: true

  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer, required: false
  belongs_to :user, required: false
  belongs_to :product
  validates :amount, presence: true, numericality: { only_integer: true }
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :orders
  has_many :comments
  validates :name, :description, :price, presence: true
  validates :price, :numericality => {:greater_than => 0}
  validates :amount, :numericality => {:greater_than => 0}
  validates :weight, :numericality => {:greater_than => 0}
  validates :calories, :numericality => {:greater_than => 0}
  validates :name, uniqueness: { scope: :category_id }
  mount_uploader :image, ImageUploader

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << %w(name description price amount weight calories)
      all.each do |product|
        csv << product.attributes.values_at(*%w(name description price amount weight calories))
      end
    end
  end

  def self.import(file, category_id)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      product = new
      product.attributes = row
                               # .to_hash.slice(:id, :name, :description, :price, :amount, :weight, :calories)
      product.category_id = category_id
      product.save!
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
      when '.csv' then Roo::CSV.new(file.path)
      when '.xls' then Roo::Excel.new(file.path, packed: nil, file_warning: :ignore)
      when '.xlsx' then Roo::Excel.new(file.path, packed: nil, file_warning: :ignore)
      else raise 'Unknown file type: #{file.original_filename}'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/basket_helper.rb
module BasketHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/download_helper.rb
module DownloadHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/office_helper.rb
module OfficeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/home.html.erb
<h1>Admin#home</h1>
<p>Find me in app/views/admin/home.html.erb</p>

app/views/admin/index.html.erb
<div style="min-height: 40em">
<table style="border-color: #0c1a1e; width: 100%">
<tr>
  <td><h2 class="text-center">Дата заказа</h2></td>
  <td><h2 class="text-center">Адрес</h2></td>
  <td><h2 class="text-center">Телефон</h2></td>
  <td><h2 class="text-center">Email</h2></td>
  <td><h2 class="text-center">  </h2></td>
</tr>
<% @customer.each do |customer| %>

    <tr>
      <td width="20%">
        <h4 class="text-center"> <%= customer.created_at %></h4>
      </td>
      <td width="20%">
       <h4 class="text-center"> <%= customer.address %></h4>
      </td>
      <td width="20%">
        <h4 class="text-center"> <%= customer.phone %></h4>
      </td>
      <td width="20%">
        <h4 class="text-center" > <%= customer.email %></h4>
      </td>
      <td width="20%">
        <button class="align-center buy"><%= link_to 'Список товаров', admin_product_path(customer) %></button>
      </td>

      </tr>
<% end %>
</table>
</div>

app/views/layouts/_footer.html.erb
<link href="https://fortawesome.github.io/Font-Awesome/assets/font-awesome/css/font-awesome.css"
      rel="stylesheet">
<!--footer start from here-->
<div class="navbar row-fluid">
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-9 col-sm-9 footer-left ">
        <br>
        <p style="color: #EFEFEF"><i class="fa fa-phone"></i> Phone (Minsk): +00 0000 000 000</p>
        <p style="color: #EFEFEF"><i class="fa fa-envelope"></i> E-mail: kerminsk@gmail.com</p>
        <p style="color: #EFEFEF"> Адрес: Гикало, 4</p>
        <br>
        <p style="color: #EFEFEF">© 2017 - Kira Emchik</p>
      </div>
      <div class="col-md-3 col-sm-3 ">
        <br>
        <h4 style="color: #EFEFEF">Время работы:</h4>
        <h4 style="color: #EFEFEF">Пн-Вс</h4>
        <h4 style="color: #EFEFEF" >9.00 - 20.00</h4>
        <br>
      </div>

    </div>
  </div>
</footer>
</div>
<!--footer start from here-->

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header main">
      <a class="main" href="#"><%= image_tag('main.png') %></a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><%= link_to 'Главная', root_path %></li>
    </ul>


      <ul class="pull-right nav navbar-nav">
        <% if user_signed_in? %>
        <% if current_user.admin? %>
            <li> <%= link_to 'Заказы', admin_index_path %></li>
        <% end %>
        <% end %>
        <% if user_signed_in? %>
        <li><%= link_to 'История заказов', office_index_path %></li>
        <% end %>
        <li> <%= link_to 'Корзина', orders_path %></li>

      <% if user_signed_in? %>
          <li style="color: #F7F7F7">
            <a> Здравствуйте <%= current_user.email %> </a>
            </li>
            <li>
            <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>
          </li>
      <% else %>
          <li class = "pull-right">
            <%= link_to 'Войти', new_user_session_path %>
            </li>
            <li>
            <%= link_to 'Зарегистрироваться', new_user_registration_path %>
          </li>
      <% end %>
      </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EatMe</title>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'home', media: 'all' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>
<body >
<header>
<%= render partial: 'layouts/header' %>
</header>
<div class='container fon'>
  <%= yield %>
</div>

<%= render partial: 'layouts/footer' %>

</body>
</html>