config/routes.rb
Rails.application.routes.draw do



  get 'admin/home'
  devise_for :admins
  get 'admin_products/index'

  # get 'basket/index'

  devise_for :users
  root to: "home#index"  #home controller, index action (method)

  resources :categories do
    resources :products
  end

  resources :products do
    resources :comments
  end

  resources :products do
    resources :orders
  end

  resources :orders
  resources :customers

  resources :customers do
    resources :orders
  end

  resources :admin

  resources :admin_products

  resources :office

  resources :download
  # get 'admin_products/update'

  resources :products do
    collection { post :import }
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :product
    validates :name, :comment, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders
  belongs_to :user, required: false
  validates :address, :phone, presence: true

  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer, required: false
  belongs_to :user, required: false
  belongs_to :product
  validates :amount, presence: true, numericality: { only_integer: true }
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :orders
  has_many :comments
  validates :name, :description, :price, presence: true
  validates :price, :numericality => {:greater_than => 0}
  validates :amount, :numericality => {:greater_than => 0}
  validates :weight, :numericality => {:greater_than => 0}
  validates :calories, :numericality => {:greater_than => 0}
  validates :name, uniqueness: { scope: :category_id }
  mount_uploader :image, ImageUploader

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << %w(name description price amount weight calories)
      all.each do |product|
        csv << product.attributes.values_at(*%w(name description price amount weight calories))
      end
    end
  end

  def self.import(file, category_id)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      product = new
      product.attributes = row
                               # .to_hash.slice(:id, :name, :description, :price, :amount, :weight, :calories)
      product.category_id = category_id
      product.save!
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
      when '.csv' then Roo::CSV.new(file.path)
      when '.xls' then Roo::Excel.new(file.path, packed: nil, file_warning: :ignore)
      when '.xlsx' then Roo::Excel.new(file.path, packed: nil, file_warning: :ignore)
      else raise 'Unknown file type: #{file.original_filename}'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @category = Category.all

  end

  def register
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/basket_helper.rb
module BasketHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/download_helper.rb
module DownloadHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/office_helper.rb
module OfficeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/index.html.erb
<br>

<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag('keks.jpg', class: 'd-block img-fluid slide') %>

    </div>
    <div class="item">
      <%= image_tag('blin.jpg', class: 'd-block img-fluid slide') %>
    </div>
    <div class="item">
      <%= image_tag('kulich.jpg', class: 'd-block img-fluid slide') %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<br>
<h1 class="text-center" style = "font-style: italic">Добро пожаловать на EatME!!!</h1>
<h2 class="text-center" style = "font-style: italic">Здесь вы можете пребрести только свежую выпечку!</h2>
<h2 class="text-center" style = "font-style: italic">Для нас важно, что бы вы получали только качественную</h2>
<h2 class="text-center" style = "font-style: italic">и вкусную продукцию.</h2>
<h2 class="text-center" style = "font-style: italic">Пусть каждый ваш день будет сладок!!!</h2>
<br>

<div id="fh5co-type" style="background-image: url(<%= asset_path 'piroz.jpg' %>) ;" data-stellar-background-ratio="0.5">
  <div class="fh5co-overlay"></div>
  <div class="container">
<h1 class="text-center" style="color:  #fff3b1; font-style: italic">Категории</h1>
      <table width="100%">
        <% @count = 0 %>
        <tr>
          <% @category.each do |category| %>
              <% @count += 1 %>
              <% if @count%6 != 0 %>
                  <td width="20%">
                    <div class="to-animate text-center">
                      <div class="fh5co-type">
                        <h3 class="with-icon icon-1"><%= link_to category.name, category_products_path(category) %></h3>
                        <p><%= category.description %></p>
                      </div>
                      <% if user_signed_in? %>
                          <% if current_user.admin? %>
                              <%= link_to 'Update', edit_category_path(category) %>
                              <%= link_to 'Destroy', category_path(category), method: :delete, data: {confirm: 'Are you sure?'} %>
                          <% end %>
                      <% end %>
                    </div>
                  </td>
              <% else %>
                  </tr>
                  <tr>
                    <td width="25%">
                      <div class="to-animate">
                        <div class="fh5co-type">
                          <h3 class="with-icon icon-1"><%= link_to category.name, category_products_path(category) %></h3>
                          <p><%= category.description %></p>
                        </div>
                        <% if user_signed_in? %>
                            <% if current_user.admin? %>
                                <%= link_to 'Update', edit_category_path(category) %>
                                <%= link_to 'Destroy', category_path(category), method: :delete, data: {confirm: 'Are you sure?'} %>
                            <% end %>
                        <% end %>
                      </div>
                    </td>
              <% end %>
          <% end %>
          </tr>
          </table>
    <div class="text-center">
      <% if user_signed_in? %>
          <% if current_user.admin? %>
              <br>
              <br>
              <%= link_to 'New category', new_category_url %>
          <% end %>
      <% end %>
    </div>
    </div>

</div>

<div class="row">
  <div class="col-xs-12">
    <br>
    <h1 class="text-center" style = "font-style: italic; color: #bb432d">У нас имеется</h1>
    <hr>
    <br>
    <div class="col-xs-4 text-center">
      <%= image_tag('keks1.png') %>
      <h3 class="text-center" style="color: #bb432d">ОНЛАЙН ЗАКАЗ</h3>
    </div>
    <div class="col-xs-4 text-center">
      <%= image_tag('keks2.png') %>
      <h3 class="text-center" style="color: #bb432d">ОТПРАВКА ЗАКАЗА В ТЕЧЕНЕЕ ДНЯ </h3>
    </div>
    <div class="col-xs-4 text-center">
      <%= image_tag('keks3.png') %>
      <h3 class="text-center" style="color: #bb432d">ВОЗМОЖНОСТЬ САМОВЫЗОВА</h3>
    </div>
    <br>
    <hr>
  </div>
</div>
<hr>
<br>

<div id="fh5co-events" data-section="events" style="background-image: url(<%= asset_path 'piroz2.jpg' %>);" data-stellar-background-ratio="0.5">
  <div class="fh5co-overlay"></div>
  <div class="container">
    <div class="row text-center fh5co-heading row-padded">
      <div class="col-md-8 col-md-offset-2 to-animate">
        <h2 class="heading">Цитаты</h2>
        <p class="sub-heading">Знать о еде человек должен не меньше, чем о математике или о своём родном языке</p>
      </div>
    </div>
    <div >
      <div class="col-md-4" style="width: 32.3333333%;">
        <div class="fh5co-event to-animate-2 text-center">
          <span class="fh5co-event-meta">КАРЛО ПЕТРИНИ</span>
          <p>"Готовить нужно не спеша, с чувством, из самых свежих органических продуктов, и есть с теми, кого любишь, за одним большим столом. Бесконечно ускоряя ритм жизни, мы лишаем себя самой жизни"</p>
        </div>
      </div>
      <div class="col-md-4" style="width: 32.3333333%;">
        <div class="fh5co-event to-animate-2 text-center">
          <span class="fh5co-event-meta">ОЛЬГА ЛИТВИНЕНКО</span>
          <p>"Культура питания начинается с высокой самооценки и самоуважения. Если вы действительно хорошо к себе относитесь, уважаете себя, вы не потащите в рот абы что и абы как"</p>
        </div>
      </div>
      <div class="col-md-4" style="width: 32.3333333%;">
        <div class="fh5co-event to-animate-2 text-center" >
          <span class="fh5co-event-meta">СЕРГЕЙ ПАРХОМЕНКО</span>
          <p>"Гастрономическое искусство приучает человека рационально и расчётливо управлять своим временем. Оно воспитывает в нас одновременно и мудрое терпение, и реакцию"</p>
        </div>
      </div>
    </div>
  </div>
</div>


<br>
<br>