config/routes.rb
Rails.application.routes.draw do



  get 'admin/home'
  devise_for :admins
  get 'admin_products/index'

  # get 'basket/index'

  devise_for :users
  root to: "home#index"  #home controller, index action (method)

  resources :categories do
    resources :products
  end

  resources :products do
    resources :comments
  end

  resources :products do
    resources :orders
  end

  resources :orders
  resources :customers

  resources :customers do
    resources :orders
  end

  resources :admin

  resources :admin_products

  resources :office

  resources :download
  # get 'admin_products/update'

  resources :products do
    collection { post :import }
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :product
    validates :name, :comment, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders
  belongs_to :user, required: false
  validates :address, :phone, presence: true

  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer, required: false
  belongs_to :user, required: false
  belongs_to :product
  validates :amount, presence: true, numericality: { only_integer: true }
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :orders
  has_many :comments
  validates :name, :description, :price, presence: true
  validates :price, :numericality => {:greater_than => 0}
  validates :amount, :numericality => {:greater_than => 0}
  validates :weight, :numericality => {:greater_than => 0}
  validates :calories, :numericality => {:greater_than => 0}
  validates :name, uniqueness: { scope: :category_id }
  mount_uploader :image, ImageUploader

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << %w(name description price amount weight calories)
      all.each do |product|
        csv << product.attributes.values_at(*%w(name description price amount weight calories))
      end
    end
  end

  def self.import(file, category_id)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      product = new
      product.attributes = row
                               # .to_hash.slice(:id, :name, :description, :price, :amount, :weight, :calories)
      product.category_id = category_id
      product.save!
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
      when '.csv' then Roo::CSV.new(file.path)
      when '.xls' then Roo::Excel.new(file.path, packed: nil, file_warning: :ignore)
      when '.xlsx' then Roo::Excel.new(file.path, packed: nil, file_warning: :ignore)
      else raise 'Unknown file type: #{file.original_filename}'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @category = Category.all

  end

  def register
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :load_product, only: [:new, :create]

    def index
      if user_signed_in?
        @order = Order.where(user_id: current_user, status: nil)
      else
        if session[:orders].blank?
          @order
        else
          @order = []
          session[:orders].each do |order|
            @order << Order.new( product_id: order['product_id'], amount: order['amount']) end
          end
      end
    end

    def new
      @order = Order.new
    end

    def create
      if user_signed_in?
        @order = @product.orders.build(order_params)
        @order.user = current_user
        if @order.save
          redirect_to category_products_path(@product.category_id)
        else
          render :new
        end
      else
        session[:orders] ||= []
        session[:orders] << {product_id: @product.id, amount: order_params[:amount] }
        redirect_to category_products_path(@product.category_id)
      end
    end

    def destroy
      if user_signed_in?
        @order = Order.find(params[:id])
        @order.destroy
      else
        session[:orders].reject!{|order| order[:product_id] == params[:product_id]}
      end
      redirect_to orders_path
    end

    private

    def order_params
      params.require(:order).permit(:amount)
    end

  def load_product
    @product = Product.find(params[:product_id])
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/basket_helper.rb
module BasketHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/download_helper.rb
module DownloadHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/office_helper.rb
module OfficeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/destroy.html.erb
<h1>Orders#destroy</h1>
<p>Find me in app/views/orders/destroy.html.erb</p>

app/views/orders/index.html.erb
<div style="min-height: 40em">
<h1 class="text-center">Корзина</h1>
<br>
<hr>
<% sum = 0.0 %>
<% sum_one = 0.0  %>
<% if @order != nil %>
<% @order.each do |order| %>

    <div class="row">
      <div class='col-xs-4'>
        <%= image_tag(order.product.image_url, class: 'image_prod') %>
      </div>
      <div class="col-xs-8">
        <div>
          <h2 style = "font-style: italic"> <%= order.product.name %> </h2>
        </div>
        <div>
          <h3>Ингридиенты</h3>
          <p style = "font-style: italic">
            <%= order.product.ingredients %>
          <p>
        </div>
        <div class="col-xs-2">
          <h5 class="text-center">Вес</h5>
          <p class="text-center" style = "font-style: italic"><%= order.product.weight %> кг.</p>
        </div>
        <div class="col-xs-3">
          <h5 class="text-center">Калорийность(в 100 г)</h5>
          <p class="text-center" style = "font-style: italic"><%= order.product.calories %> ккал.</p>
        </div>
        <div class="col-xs-3">
          <h5 class="text-center">Цена</h5>
          <p class="text-center" style = "font-style: italic"><%= order.product.price %> руб.</p>
        </div>
        <div class="col-xs-3">
          <h5 class="text-center">Количество</h5>
          <p class="text-center" style = "font-style: italic"><%= order.amount %></p>
        </div>

        <div class="col-xs-3">
          <h4 class="text-center">Итоговая сумма:</h4>
          <h4 class="text-center" style = "font-style: italic"><%= sum_one = order.product.price*order.product.amount %> руб.</h4>
        </div>
        <div class="col-xs-6 buy text-center buy7">
          <br>
          <br>
          <%= link_to 'Просмотреть', product_comments_path(order.product.id) %>
        </div>
        <div class="col-xs-3 buy2">
          <br>
          <% if user_signed_in? %>
              <%= link_to 'Удалить', order_path(order), method: :delete, data: {confirm: 'Are you sure?'} %>
              <% else %>
          <%= link_to 'Удалить', order_path(order.product.id), method: :delete, data: {confirm: 'Are you sure?'} %>
          <%end %>
        </div>
        <% sum += sum_one %>
      </div>
    </div>
    <hr>
<% end %>
<%end %>
<h2 class="text-right" style = "font-style: italic">Итого: <%= sum %> руб.</h2>
<div class="col-xs-5"></div>
<% if @order != nil %>
<div class="col-xs-2 buy">
  <button class="button"><%= link_to 'Купить', new_customer_path %></button>
</div>
<br><br>
<%end%>
</div>
</div>

app/views/orders/new.html.erb
<div class='row' style="min-height: 40em">
  <div class="col-xs-3"></div>
  <div class='col-xs-6 text-center'>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
     <h3>Вы можете заказать товар в количестве: <%= @product.amount %> </h3>

    <%= simple_form_for @order, url: product_orders_path(@product, @order) do |f| %>

        <p>
          <%= f.input :amount, collection: 1..@product.amount, hint: 'Введите желаемое количество товара',selected: 1, input_html: { class: 'input2' }%>
        </p>

        <p>
          <%= f.submit 'Save', data: {confirm: 'Товар добавлен в корзину'} %>
        </p>
    <% end %>
  </div>
</div>