config/routes.rb
Rails.application.routes.draw do



  get 'admin/home'
  devise_for :admins
  get 'admin_products/index'

  # get 'basket/index'

  devise_for :users
  root to: "home#index"  #home controller, index action (method)

  resources :categories do
    resources :products
  end

  resources :products do
    resources :comments
  end

  resources :products do
    resources :orders
  end

  resources :orders
  resources :customers

  resources :customers do
    resources :orders
  end

  resources :admin

  resources :admin_products

  resources :office

  resources :download
  # get 'admin_products/update'

  resources :products do
    collection { post :import }
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :product
    validates :name, :comment, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders
  belongs_to :user, required: false
  validates :address, :phone, presence: true

  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer, required: false
  belongs_to :user, required: false
  belongs_to :product
  validates :amount, presence: true, numericality: { only_integer: true }
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :orders
  has_many :comments
  validates :name, :description, :price, presence: true
  validates :price, :numericality => {:greater_than => 0}
  validates :amount, :numericality => {:greater_than => 0}
  validates :weight, :numericality => {:greater_than => 0}
  validates :calories, :numericality => {:greater_than => 0}
  validates :name, uniqueness: { scope: :category_id }
  mount_uploader :image, ImageUploader

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << %w(name description price amount weight calories)
      all.each do |product|
        csv << product.attributes.values_at(*%w(name description price amount weight calories))
      end
    end
  end

  def self.import(file, category_id)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      product = new
      product.attributes = row
                               # .to_hash.slice(:id, :name, :description, :price, :amount, :weight, :calories)
      product.category_id = category_id
      product.save!
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
      when '.csv' then Roo::CSV.new(file.path)
      when '.xls' then Roo::Excel.new(file.path, packed: nil, file_warning: :ignore)
      when '.xlsx' then Roo::Excel.new(file.path, packed: nil, file_warning: :ignore)
      else raise 'Unknown file type: #{file.original_filename}'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def index
    @customer = Customer.order(created_at: :desc)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @category = Category.all

  end

  def register
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :load_category

  def index
    @products = @category.products
    @category_id
    if params[:sort].present?
      @products = @category.products.order(price: :desc)
    end
    if params[:sort_d].present?
      @products = @category.products.order(price: :asc)
    end
  end

  def show
    @product = @category.products.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = @category.products.build(product_params)
    if @product.save
      redirect_to category_products_path(@category)
    else
      render :new
    end
  end

  def edit
    @product = @category.products.find(params[:id])
  end

  def update
    @product = @category.products.find(params[:id])
    if @product.update(product_params)
      redirect_to category_products_path(@category)
    else
      render :edit
    end
  end

  def destroy
    @product = @category.products.find(params[:id])
    @product.destroy
    redirect_to category_products_path(@category)
  end

  def import
    Product.import(params[:file], @category_id)
    redirect_to root_path, notice: 'Products imported.'
  end

  private

  def load_category
    @category = Category.find(params[:category_id])
    @category_id = @category.id
  end

  def product_params
    params.require(:product)
        .permit(:name, :description, :ingredients, :description, :calories, :image,:weight, :price, :amount)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/basket_helper.rb
module BasketHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/download_helper.rb
module DownloadHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/office_helper.rb
module OfficeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div id="fh5co-type" style="background-image: url(<%= asset_path 'pech.jpg' %>) ; " data-stellar-background-ratio="0.5">
  <div class="fh5co-overlay"></div>
  <div class="container" >
    <div class="col-xs-3"></div>
    <div class="col-xs-5">
    <%= simple_form_for [@category, @product] do |f| %>
        <p>
          <%= f.file_field :image %>
        </p>

        <p>
          <%= f.input :name, as: :text, input_html: { class: 'input text' },  label_html: { class: 'label' } %>
        </p>

        <p>
          <%= f.input :description, as: :text, input_html: { class: 'input' },  label_html: { class: 'label' } %>
        </p>

        <p>
          <%= f.input :ingredients, as: :text, input_html: { class: 'input' },  label_html: { class: 'label' } %>
        </p>

        <p>
          <%= f.input :weight,  input_html: { class: 'input' },  label_html: { class: 'label' } %>
        </p>

        <p>
          <%= f.input :calories, input_html: { class: 'input' },  label_html: { class: 'label' } %>
        </p>

        <p>
          <%= f.input :price, input_html: { class: 'input' },  label_html: { class: 'label' } %>
        </p>

        <p>
          <%= f.input :amount, input_html: { class: 'input' },  label_html: { class: 'label' } %>
        </p>

        <p class="text-center">
          <%= f.submit 'Save', :class => 'save' %>
        </p>
    <% end %>
    </div>
    </div>
  </div>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/distroy.html.erb
<h1>Products#distroy</h1>
<p>Find me in app/views/products/distroy.html.erb</p>

app/views/products/edit.erb
<%= render 'form' %>

app/views/products/index.html.erb
<div style="min-height: 50em">
<h1 class="text-center" style = "font-style: italic"><%= @category.name %></h1>
<% @sort_d = true %>
<% @sort = true %>
<div class="row">
  <div class="col-xs-1"></div>
  <div class="col-xs-8 buy2">
    <li><h3 ><%= link_to 'Назад' , root_path %></h3></li>
  </div>
  <div class="col-xs-3 sortirovka">
    <li class="dropdown" >
      <a id="drop1" href="#" class="dropdown-toggle " data-toggle="dropdown">
        <h3 style="color: #B00100">Сортировать</h3>
      </a>
      <ul class="dropdown-menu">
        <li><a href="#"><%= link_to 'от большей цены к меньшей', category_products_path(@category.id, sort: @sort) %></a></li>
        <li><a href="#"><%= link_to 'от меньшей цены к большей', category_products_path(@category.id, sort_d: @sort_d) %></a></li>
        <li class="divider"></li>
      </ul>
    </li>
  </div>
</div>
<hr style="border-top: 1px solid #000000;">
    <% @products.each do |product| %>
        <div class="row">
          <div class='col-xs-4'>
            <br>
            <%= image_tag(product.image_url, class: 'image_prod') if product.image? %>
          </div>
          <div class="col-xs-8">
            <div>
              <h2 class="text-center" style = "font-style: italic";> <%= product.name %> </h2>
            </div>
            <div>
              <h3>Ингредиенты</h3>
              <p style = "font-style: italic">
                <%= product.ingredients %>
              <p>
            </div>
            <div>
              <h3>Описание</h3>
              <p style = "font-style: italic"><%= product.description %></p>
            </div>
            <div class="col-xs-3">
              <h5 class="text-center">Вес</h5>
              <p class="text-center" style = "font-style: italic"><%= product.weight %> кг.</p>
            </div>
            <div class="col-xs-3">
              <h5 class="text-center">Калорийность(в 100 г)</h5>
              <p class="text-center" style = "font-style: italic"><%= product.calories %> ккал.</p>
            </div>
            <div class="col-xs-3">
              <h5 class="text-center">Цена</h5>
              <p class="text-center" style = "font-style: italic"><%= product.price %> руб.</p>
            </div>
            <div class="col-xs-3">
              <%= link_to image_tag('basket.png', class: 'backet'), new_product_order_path(product) %>
            </div>
            <div class="buy text-center buy7">
              <%= link_to 'Просмотреть', product_comments_path(product) %>
            </div>
          </div>
          <% if user_signed_in? %>
              <% if current_user.admin? %>
                  <div class="col-xs-1"></div>
                    <div class="col-xs-4">
                      <button class="button7 buy">
                        <%= link_to 'Update', edit_category_product_path(@category, product) %>
                      </button>
                      <button class='button7 buy'>
                        <%= link_to 'Destroy', category_product_path(@category, product), method: :delete, data: {confirm: 'Are you sure?'} %>
                      </button>
                    <br>
                  </div>
              <% end %>
          <% end %>
      </div>
        <hr style="border-top: 1px solid #000000;">
    <% end %>


<% if user_signed_in? %>
    <% if current_user.admin? %>
      <div class="row">
        <div class="col-xs-1"></div>
        <div class=class="col-xs-4">
        <button class="bottom-aligned buy">
          <%= link_to 'New product', new_category_product_path %>
          </button>
          <button class="bottom-aligned buy">
          <%= link_to 'Скачать данные в Excel', download_index_path(category_id: @category_id, format: 'xls')%>
            </button>
            <button class="bottom-aligned buy">
            <%= link_to 'Скачать данные в csv', download_index_path(category_id: @category_id, format: 'csv')%>
        </button>
          <h2>Импортировать продукты</h2>
          <div class="col-xs-1"></div>
          <div class="col-xs-4">
          <%= form_tag import_products_path(category_id: @category_id), multipart: true do %>
              <%= file_field_tag :file %>
                <br>
              <%= submit_tag 'Import' %>
          <% end %>
            <br>
          </div>
          <br>
          <br>
        </div>
      </div>
  <% end %>
<% end %>
</div>

app/views/products/show.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
  </tr>

  <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.ingredients %></td>
        <td><%= product.description %>
        <td><%= product.weight %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product_path(product) %></td>
        <td><%= link_to 'Update', products_url(product) %></td>
        <td><%= link_to 'Destroy', products_path(product), method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
      <tr>
        <td></td>
      </tr>
  <% end %>
  <%= link_to 'New product', new_product_url %>
</table>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>